Adding code base

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -32,6 +32,7 @@ jobs:
           echo "TS_BUSINESS_TAXONOMY=$(cat ./src/ts/business_taxonomy.txt)" >> $GITHUB_ENV
           echo "TS_STATIC_RULES=$(cat ./src/ts/static_rules.txt)" >> $GITHUB_ENV
           echo "TS_LOOKUP_RULES=$(cat ./src/ts/lookup_rules.txt)" >> $GITHUB_ENV
+          echo "TS_CODE_BASE=$(cat ./src/ts/code_base.txt)" >> $GITHUB_ENV
           
           mkdir tmp
           mkdir tmp/ts
@@ -55,6 +56,11 @@ jobs:
             echo $LATEST_LOOKUP_RULES > ./tmp/raw/lookup_rules.json 
             echo "LATEST_TS_LOOKUP_RULES=$(cat ./tmp/raw/lookup_rules.json | jq '.data.function.deployedAt')" >> $GITHUB_ENV
             (echo $LATEST_LOOKUP_RULES | jq '{lookupRules:.data.function.code}') > ./tmp/assets/lookup_rules.json
+            
+            LATEST_CODE_BASE=$(curl --fail --location --request GET --header "Authorization: Bearer ${{secrets.ACCESS_TOKEN}}" --url "${{env.BASE_URL}}/functions/${{env.CODE_BASE_ID}}" || { exit 1;})
+            echo $LATEST_CODE_BASE > ./tmp/raw/code_base.json 
+            echo "LATEST_TS_CODE_BASE=$(cat ./tmp/raw/code_base.json | jq '.data.function.deployedAt')" >> $GITHUB_ENV
+            (echo $LATEST_CODE_BASE | jq '{code:.data.function.code}') > ./tmp/assets/code_base.json
             
       - name: Update Config Taxonomy if needed
         if: ${{ env.LATEST_TS_CONFIG_TAXONOMY != env.TS_CONFIG_TAXONOMY }}
@@ -137,10 +143,18 @@ jobs:
           echo "1" > ./src/deploy/lookup_rules
           echo "GIT_PUSH_REQUIRED=1" >> $GITHUB_ENV
           
+      - name: Update Code Base if needed
+        if: ${{ env.LATEST_TS_CODE_BASE != env.TS_CODE_BASE }}
+        run: |
+          cp ./tmp/assets/code_base.json ./src/assets/code_base.json
+          echo $LATEST_TS_CODE_BASE > ./src/ts/code_base.txt
+          echo "1" > ./src/deploy/code_base
+          echo "GIT_PUSH_REQUIRED=1" >> $GITHUB_ENV
+          
       - name: Bundle code and Deploy to Segemnt
         run: |
           LIBRARY=$(jq -s 'reduce .[] as $item({}; . * $item)' ./src/assets/config_taxonomy.json ./src/assets/business_taxonomy.json ./src/assets/static_rules.json ./src/assets/lookup_rules.json)
-          FUNCTION="{}"
+          FUNCTION=$(jq '.code' ./src/assets/code_base.json)
           PAYLOAD=$(jq '{functionId: "\(.fn_id)", code: "const library=\(.library);\(.base)"}' <<EOF
           {"fn_id":"${{env.CORE_INGESTION_FUNCTION_ID}}","library": $LIBRARY, "base": "$FUNCTION"}
           EOF) 
